config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "stocks#index"

  resources :stocks do
    collection do
      get 'search'
    end
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  get 'stocks/autocomplete_stocks/:term' => 'stocks#autocomplete_stocks'

  resources :items do
    collection do
      get 'addto'
    end
  end
  resources :orders do
    collection do
      get 'confirm'
    end
  end
  resources :admins, only: [:index] do
    resources :userpermissions, only: [:index, :update]
  end
  resources :users, only: [:index, :show, :new] do
    collection do
      get 'payments'
      post 'creditcard_regist'
      delete 'creditcard_destroy'
    end
  end
  resources :carts
  resources :categories do
    collection do
      get 'admin_category'
    end
    resources :sub_categories
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :carts
  has_many :orders
  has_many :reviews
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :quantitychecker_moveto_buylater


  def index
    # アカウントサービス画面
    @stocks = Stock.all
  end

  def show
    # マイストア画面
    @user = current_user

    # サブカテゴリー別に商品を表示させる
    @categories = Category.all
    @subcategories = SubCategory.all
    @stocks = []
      @subcategories.each do |sub_category|
        stock = Stock.where(sub_category_id: sub_category.id)
        @stocks << stock if stock.length != 0
      end

    #最近のn件の注文
    if user_signed_in?
      quantitychecker_moveto_buylater
      @cart = current_user.carts.new
      range = Date.current.ago(14.days).beginning_of_day..Date.current.end_of_day
      @recentorders = current_user.orders.where(created_at: range).length
    end
  end

  def payments
  	# 支払いオプション画面
  	@user = current_user
   	# 現在の年を格納する（クレジットカード情報登録用）
    @year = Time.current.in_time_zone('Tokyo').strftime("%Y").to_i

    # そのユーザにカードが登録されているかを調べる(メソッドはapplication_controller.rbに記載)
    @existuser_flg = cardusercheck


    # Payjpに登録されているそのユーザidを持つユーザのクレジットカード情報を取得する。
    if @existuser_flg == true
      @customer_creditcards = gets_usercardinfo
      @default_cardid = gets_userdefaultcardid
    end
  end

  def creditcard_regist
  	# pay.jpにクレジットカード情報を登録する

  	# トークン作成
    token = Payjp::Token.create(
      card: {
        number: card_params[:number],
        cvc: card_params[:cvc],
        exp_year: card_params[:year],
        exp_month: card_params[:month],
        name: card_params[:name]
      }
    )
    @token_id = token.id


    # Pay.jpへのカード追加に関わる処理
    # そのユーザにカードが登録されているかを調べる(privateメソッド)
    @existuser_flg = cardusercheck

    if @existuser_flg == true
      #既存顧客：すでに１枚以上カードがあり、そこに追加する場合
      customer = gets_usercardinfo

      #カード名義、カード番号(下4桁)、有効期限(月・年)すべてが同じものがある場合、登録できないようにする。
      cards = customer.cards.all
      samecard_flg = false
      cards.each do |card|
        if card_params[:number][-4,4] == card.last4 && card_params[:month] == card.exp_month.to_s && card_params[:year] == card.exp_year.to_s
          samecard_flg = true
        end
      end

      #  samecard_flgがfalseのまま：同じカードが存在しないことになるので、カードを作成する。
      if samecard_flg == false
        customer.cards.create(
            card: @token_id
          )
      end

    else
      #新規顧客：１枚もカードがない場合
      # Pay.jpに顧客を作成（カード情報の保存に必要）
      Payjp::Customer.create(
        id: current_user.id,
        email: current_user.email,
        card: @token_id
      )
    end

  	# お支払いオプションページに戻る
    # アラートを出す
  	redirect_to payments_users_path
  end

  def creditcard_destroy
    # 顧客情報取得
    # 取得したparams[:id]と合致したものを削除する
    @customer_creditcards = gets_usercardinfo
    @customer_creditcards.cards.data.each do |customer_creditcard|
      if customer_creditcard.id == params[:id]
        card = @customer_creditcards.cards.retrieve(params[:id])
        card.delete
      end
    end
    redirect_to payments_users_path
  end

  private
  def card_params
  	params.permit(:name, :number, :month, :year, :cvc)
  end

  def delete_card_params
    params.permit(:id, :name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
= render "shared/header"
.mainwindow
  .mainwindow__title
    アカウントサービス
  .mainwindow__topboxleft
    = link_to orders_path, class: "clearfix unit_box" do
      .unit1
        .unit1__boximage
          =image_tag "orders.png", width: 96 , height: 54
        .unit_boxname
          .unit__boxname
            %span 注文履歴
          .unit__boxdetail
            %span 配送状況の確認・返品手続き
    = link_to users_path, class: "clearfix unit_box" do
      .unit2
        .unit2__boximage
          =image_tag "addresses.png", width: 87 , height: 68
        .unit_boxname
          .unit__boxname
            %span アドレス帳
          .unit__boxdetail
            %span 登録住所の追加・変更
  .mainwindow__topboxcenter
    = link_to edit_user_registration_path, class: "clearfix unit_box" do
      .unit1
        .unit1__boximage
          =image_tag "security.png", width: 96 , height: 72
        .unit_boxname
          .unit__boxname
            %span サインインとセキュリティ
          .unit__boxdetail
            %span アカウント情報の変更
    = link_to payments_users_path, class: "clearfix unit_box" do
      .unit2
        .unit1__boximage
          =image_tag "payments.png", width: 80 , height: 54
        .unit_boxname
          .unit__boxname
            %span お支払い方法
          .unit__boxdetail
            %span お支払い方法の追加・変更
  .mainwindow__topboxright
    = link_to users_path, class: "clearfix unit_box" do
      .unit1
        .unit1__boximage
          =image_tag "prime.png", width: 96 , height: 72
        .unit_boxname
          .unit__boxname
            %span プライム
          .unit__boxdetail
            %span 会員特典とお支払い方法の確認
    = link_to users_path, class: "clearfix unit_box" do
      .unit2
        .unit2__boximage
          =image_tag "giftcard.png", width: 82 , height: 54
        .unit_boxname
          .unit__boxname
            %span Amazonギフト券
          .unit__boxdetail
            %span 残高の確認・ギフト券の登録
  .mainwindow__borderline
  .mainwindow__middleboxleft
    .unit3
      .unit3__boxtitle
        デジタルコンテンツとデバイス
      .unit3__boxlinks
        = link_to "Amazon Driveの管理", ""
      .unit3__boxlinks
        = link_to "アプリライブラリと端末の管理", ""
      .unit3__boxlinks
        = link_to "コンテンツと端末の管理", ""
      .unit3__boxlinks
        = link_to "ゲーム&PCソフトダウンロードライブラリ", ""
      .unit3__boxlinks
        = link_to "Amazon Musicの設定", ""
      .unit3__boxlinks
        = link_to "Amazon ビデオの設定", ""
    .unit4
      .unit4__boxtitle
        お買い物設定
      .unit4__boxlinks
        = link_to "非表示にした注文の表示",""
      .unit4__boxlinks
        = link_to "言語設定の変更",""
      .unit4__boxlinks
        = link_to "マイリスト",""
      .unit4__boxlinks
        = link_to "プロフィール",""
      .unit4__boxlinks
        = link_to "ソーシャル設定",""
    .unit5
      .unit5__boxtitle
        メールマガジン
      .unit5__boxlinks
        = link_to "デリバーズ(購読Eメール)の設定",""
  .mainwindow__middleboxmiddle
    .unit3
      .unit3__boxtitle
        Eメールとメッセージ
      .unit3__boxlinks
        = link_to "広告表示の設定",""
      .unit3__boxlinks
        = link_to "情報配信サービスの設定",""
      .unit3__boxlinks
        = link_to "メッセージセンター",""
      .unit3__boxlinks
        = link_to "Amazon.co.jp お知らせEメール",""
    .unit4
      .unit4__boxtitle
        その他のアカウント
      .unit4__boxlinks
        = link_to "出品用アカウント",""
      .unit4__boxlinks
        = link_to "Amazon Webサービスアカウント",""
      .unit4__boxlinks
        = link_to "Audibleアカウント",""
      .unit4__boxlinks
        = link_to "Amazonログインの設定",""
      .unit4__boxlinks
        = link_to "Amazon Business",""
      .unit4__boxlinks
        = link_to "Twitch アカウント設定の管理",""
  .mainwindow__middleboxright
    .unit3
      .unit3__boxtitle
        その他の支払い方法
      .unit3__boxlinks
        = link_to "1-Click 設定",""
      .unit3__boxlinks
        = link_to "各種クレジットカードの紹介・入会情報",""
      .unit3__boxlinks
        = link_to "Amazonコインの獲得・利用履歴の確認",""
      .unit3__boxlinks
        = link_to "Amazon Payの購入履歴の確認",""
      .unit3__boxlinks
        = link_to "クーポン",""
      .unit3__boxlinks
        = link_to "Amazonポイントの獲得・利用履歴の確認",""
      .unit3__boxlinks
        = link_to "パートナーポイントの管理",""
    .unit4
      .unit4__boxtitle
        お買い物プログラム
      .unit4__boxlinks
        = link_to "バーチャルダッシュ",""
      .unit4__boxlinks
        = link_to "Amazon定期おトク便情報の管理",""
.historybox
  .title
    最近閲覧した商品とおすすめ商品
  .btfContent1__uber-widget-ns-images
    - @stocks.shuffle.first(15).each do |stock|
      = link_to image_tag(stock.image), stock_path(stock), width:200, height:200
= render "shared/footer"

app/views/users/payments.html.haml
=render "shared/header"
.payoption
  .payoption__title
    = link_to "アカウントサービス", users_path
    > お支払いオプションを管理
  .payoption__message
    こちらがお客様のAmazonアカウントに保存されているお支払い方法です。
  .payoption__leftbox
    =link_to "1-Click設定の管理",""
    .br
    =link_to "Kindleの支払い設定を管理",""
    .br
    =link_to "現在のご注文のお支払い方法を編集",""
  .payoption__rightbox
    .payoption__rightbox__topbox
      .top
        .top__title
          ご登録のクレジットカード
        .top__limit
          有効期限
    .payoption__rightbox__creditlist
      -if @existuser_flg == true
        - @customer_creditcards.cards.data.each do |creditcard|
          .credit
            .credit__mark
              = image_tag "visa_mark.gif", width:40
            .credit__text
              = creditcard.brand
              下4桁
              = creditcard.last4
            .credit__limit
              = creditcard.exp_month
              #{"/"}
              = creditcard.exp_year
            .credit__listdownmark
              %i.fa.fa-angle-down
          .textarea
            .textarea__leftbox
              %b
                クレジットカード名義人
              .br
              = creditcard.name
            .textarea__rightbox
              %b
                請求先住所
                = @user.first_name
                = @user.last_name
              .br
              = @user.postal_code
              .br
              = @user.pref
              = @user.city
              .br
              = @user.apartment_roomnumber
              .br
              日本
              .br
              = @user.telnumber
              .br
              = link_to "削除",creditcard_destroy_users_path(@user, params: creditcard ), method: :delete ,class: "card-graybutton-mini"
    .payoption__rightbox__toptitle
      残高
    .payoption__rightbox__giftcardbox
      .gift
        .gift__mark
          = image_tag "amazongiftcard.png", width:40
        .gift__text
          Amazonギフト券
        .gift__balance
          ¥0
        .gift__link
          =link_to "ギフト券を購入", ""
          |
          =link_to "ギフト券を登録",""
    .payoption__rightbox__new
      新しいお支払い方法を追加
    .borderline
    .payoption__rightbox__credit
      .payoption__rightbox__credit__leftbox
        .payoption__rightbox__credit__leftbox__title
          クレジットカード
        .payoption__rightbox__credit__leftbox__message
          以下のクレジットカードをご利用いただけます
        .payoption__rightbox__credit__leftbox__addlink
          =link_to "カードを追加",""
        .payoption__rightbox__credit__leftbox__addtext
          カード情報を入力してください
        = form_tag(action: :creditcard_regist, method: :post) do
          .payoption__rightbox__credit__leftbox__name
            .payoption__rightbox__credit__leftbox__name__label
              カード名義人（半角ローマ字）
            .payoption__rightbox__credit__leftbox__name__textfield
              %input{ name: "name", size: "20", type: "text" }
          .payoption__rightbox__credit__leftbox__number
            .payoption__rightbox__credit__leftbox__number__label
              カード番号
            .payoption__rightbox__credit__leftbox__number__textfield
              %input{ name: "number", size: "20", type: "text"}
          .payoption__rightbox__credit__leftbox__limit
            .payoption__rightbox__credit__leftbox__limit__label
              有効期限
            .payoption__rightbox__credit__leftbox__limit__monthbox
              %select{ name: "month"}
                - 11.times do |m|
                  %option{ value: "#{m + 1}"} #{m + 1}
                %option{ value: "12"} 12
            .payoption__rightbox__credit__leftbox__limit__yearbox
              %select{ name: "year"}
                - 21.times do |y|
                  %option{ value: "#{y + @year}" } #{y + @year}
          .payoption__rightbox__credit__leftbox__cvc
            .payoption__rightbox__credit__leftbox__cvc__label
              CVC（セキュリティコード）
            .payoption__rightbox__credit__leftbox__cvc__textfield
              %input{ name: "cvc", size: "5", type: "text" }
          .payoption__rightbox__credit__leftbox__addbutton
            %input{ type:"submit", value:"クレジットカードを追加", class: "addpaymentcreditbutton"}
      .payoption__rightbox__credit__rightmarkbox
        =image_tag "card_brand.png", width:150
    .borderline
    .payoption__rightbox__cellphone
      .payoption__rightbox__cellphone__leftbox
        .payoption__rightbox__cellphone__leftbox__title
          携帯決済
        .payoption__rightbox__cellphone__leftbox__message
          携帯決済がご利用いただけない場合については
          =link_to "こちら",""
        .payoption__rightbox__cellphone__leftbox__addlink
          =link_to "新しいアカウントを追加",""
        .payoption__rightbox__cellphone__leftbox__addtext
          携帯電話会社とアカウントタイプを選択してください。
        .payoption__rightbox__cellphone__leftbox__carriername
          携帯電話会社（docomoまたはau）を選択
        .payoption__rightbox__cellphone__leftbox__carrierbox
          %select{ name: "carrier"}
            %option{ value: "docomo" } docomo
            %option{ value: "au" } au
        .payoption__rightbox__cellphone__leftbox__accounttype
          アカウントタイプ
          =link_to "説明",""
        .payoption__rightbox__cellphone__leftbox__accountbox
          %select{ name: "accounttype"}
            %option{ value: "personal" } 個人用
            %option{ value: "work" } 仕事用
            %option{ value: "family" } 家族用
            %option{ value: "son" } 子供用（息子）
            %option{ value: "daughter" } 子供用（娘）
            %option{ value: "otherfamily" } その他家族用
            %option{ value: "other" } その他
        .payoption__rightbox__cellphone__leftbox__addbutton
          =link_to "続行","" , class: "addpaymentcarrierbutton"
      .payoption__rightbox__cellphone__rightboxmark
        =image_tag "carrier_brand.png", width:50


=render "shared/footer"

app/views/users/show.html.haml
= render "shared/header"
.wrapper
  .mystorefirstheader
    .ul.clearfix
      .li
        マイストア
      .li
        表示履歴
      .li
        お客様へのおすすめ
      .li
        おすすめ商品を正確にする
      .li
        プロフィール
      .li
        詳しくはこちら
  .mystoresecondheader
    .mystoresecondheader__avatar
      = image_tag "face_icon.png", width: 80, height: 80
    .mystoresecondheader__name
      = @user.first_name
      = @user.last_name
      .br
      さんのストア
    .mystoresecondheader__recentorder
      %span
        お客様のご注文
      .br
      %span
        - if user_signed_in?
          = @recentorders
        - else
          0
        件の最近のご注文
      .br
      = link_to "詳細を表示", orders_path
    .mystoresecondheader__prime
      %span
        プライム会員の特典
      .br
      %span
        無制限のフォトストレージ
      .br
      = link_to "詳細を表示",""
    .mystoresecondheader__audible
      %span
        AUDIBLE：無料体験で聴こう
      .br
      %span
        M-1グランプリ爆笑ネタ配信中
      .br
      = link_to "今すぐチェック",""
    .mystoresecondheader__starting
      %span
        ご利用開始年度
      .br
      = @user.created_at.in_time_zone('Tokyo').strftime("%Y")
  .mystoremainwindow
    .mystoremainwindow__recommendtitle
      = @user.first_name
      = @user.last_name
      さんへのおすすめ
    .mystoremainwindow__recommendcontents.clearfix
      - @stocks.each do |s|
        .mystoremainwindow__recommenditems
          .mystoremainwindow__recommenditems__images
            = link_to image_tag(s.first.image), category_sub_category_path(s.first.category_id, s.first.sub_category_id)
          .mystoremainwindow__recommenditems__title
            = s.first.sub_category.name
          .mystoremainwindow__recommenditems__count
            = s.count
            商品

      -# - @stock_one.each do |stock_one|
      -#   - binding.pry
      -#   .mystoremainwindow__recommenditems
      -#     .mystoremainwindow__recommenditems__images
      -#       = link_to image_tag(stock_one.image), category_sub_category_path(stock_one.category_id, stock_one.sub_category_id)
      -#     .mystoremainwindow__recommenditems__title
      -#       = stock_one.sub_category.name
      -#     .mystoremainwindow__recommenditems__count
      -#       = stock_one.count
            -# - @stocks.each do |stock_count|
            -#   = stock_count.count
            -#   商品
= render "shared/footer"