config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "stocks#index"

  resources :stocks do
    collection do
      get 'search'
    end
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  get 'stocks/autocomplete_stocks/:term' => 'stocks#autocomplete_stocks'

  resources :items do
    collection do
      get 'addto'
    end
  end
  resources :orders do
    collection do
      get 'confirm'
    end
  end
  resources :admins, only: [:index] do
    resources :userpermissions, only: [:index, :update]
  end
  resources :users, only: [:index, :show, :new] do
    collection do
      get 'payments'
      post 'creditcard_regist'
      delete 'creditcard_destroy'
    end
  end
  resources :carts
  resources :categories do
    collection do
      get 'admin_category'
    end
    resources :sub_categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :stock
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
  accepts_nested_attributes_for :sub_categories, reject_if: :all_blank

end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :sub_category, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderdetails
  belongs_to :user
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  belongs_to :order
  belongs_to :stock
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stock
  belongs_to :user

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :carts
  has_many :orderdetails
  has_many :reviews
  scope :autocomplete, ->(term) { where("name LIKE ?", "%#{term}%").order(:name) }
  belongs_to :sub_category
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category, optional: true
  has_many :stocks
  accepts_nested_attributes_for :stocks

  def self.import(file)
    CSV.foreach('db/Sub-categories-Sub-categories.csv') do |row|
      SubCategory.create(:category_id => row[0], :name => row[1])
      SubCategory.save! row.to_hash
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :carts
  has_many :orders
  has_many :reviews
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :permission_check

  def index
    # 注文履歴最新５件
    @recentorders = Order.order(created_at: :desc).limit(10)
    # 在庫数５未満の商品一覧
    @limitedstocks = []
    @stocks = Stock.all
    @stocks.each do |stock|
      if stock.current_stock <= 5
        @limitedstocks += stock
      end
    end
  end

  private
  def permission_check
    #権限制御 トップページが出来上がってから動作させる。
    if user_signed_in?
      if current_user.admin_flg == nil
        render "errors/forbidden"
      end
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 最初に作成するユーザであれば、無条件でadmin_flgをtrueにする
  def privilege_elevate
    @users = User.all
    if @users.empty?
      return true
    else
      return false
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
	# 数量セレクトボックスの配列作成
  def quantity_array_maker(stock)
    @current_stock_array = []
    stock.current_stock.times do |current_stock|
      if current_stock < 10
        @current_stock_array << [current_stock + 1,current_stock + 1]
      else
        break
      end
    end
    return @current_stock_array
  end

  def quantityselecter(cart)
    return cart.quantity - 1
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  # 1注文とその注文に紐付いている注文詳細を取得する
  def order_orderdetails(order,range)
    @orderdetails = order.orderdetails.where(created_at: range)
    return @orderdetails
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper

  def amazoncreditcard(sell_price)
    discount = sell_price - 5000
    if discount > 0
      return discount
    else
      return 0
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.haml
= render "shared/adminheader"
= render "shared/leftsidebar"
.adminmainwindow
  .adminmainwindow__boxes
    .adminmainwindow__boxes__orders
      .adminmainwindow__boxes__orders__title
        [注文履歴 最新５件]
      .adminmainwindow__boxes__orders__detail
        %table
          %tr
            - if @recentorders.present?
              %th ID
              %th 注文金額
              %th 合計送料
              %th 合計金額
            - else
              注文はありません。
          - @recentorders.each do |recentorder|
            %tr
              %td
                = recentorder.id
              %td
                = recentorder.total.to_s(:delimited)
              %td
                = recentorder.total_shippingcost.to_s(:delimited)
              %td
                = (recentorder.total + recentorder.total_shippingcost).to_s(:delimited)
    .adminmainwindow__boxes__stocks
      .adminmainwindow__boxes__stocks__title
        [在庫数 5未満の商品一覧]
      .adminmainwindow__boxes__stocks__detail
        %table
          %tr
            - if @limitedstocks.present?
              %th ID
              %th 名前
              %th 画像
              %th メーカー
              %th 現在在庫
            - else
              在庫数5未満の商品はありません。
          - @limitedstocks.each do |limitedstock|
            %tr
              = limitedstock.id
            %tr
              = limitedstock.name
            %tr
              = image_tag limitedstock.image, width:100
            %tr
              = limitedstock.maker
            %tr
              = limitedstock.current_stock.to_s(:delimited)
= render "shared/adminfooter"

app/views/admins/index.html.haml
= render "shared/adminheader"
.admin-wrapper
  = render "shared/leftsidebar"
  .admin-wrapper
    .adminmainwindow
      .adminmainwindow__boxes
        .adminmainwindow__boxes__orders
          .adminmainwindow__boxes__orders__title
            %h3
              注文履歴 最新５件
          .adminmainwindow__boxes__orders__detail
            %table
              %tr
                - if @recentorders.present?
                  %th ID
                  %th 注文金額
                  %th 合計送料
                  %th 合計金額
                - else
                  注文はありません。
              - @recentorders.each do |recentorder|
                %tr
                  %td
                    = recentorder.id
                  %td
                    = recentorder.total.to_s(:delimited)
                  %td
                    = recentorder.total_shippingcost.to_s(:delimited)
                  %td
                    = (recentorder.total + recentorder.total_shippingcost).to_s(:delimited)
        .adminmainwindow__boxes__stocks
          .adminmainwindow__boxes__stocks__title
            %h3
              在庫数 5未満の商品一覧
          .adminmainwindow__boxes__stocks__detail
            %table
              %tr
                - if @limitedstocks.present?
                  %th ID
                  %th 名前
                  %th 画像
                  %th メーカー
                  %th 現在在庫
                - else
                  在庫数5未満の商品はありません。
              - @limitedstocks.each do |limitedstock|
                %td
                  = limitedstock.id
                %td
                  = limitedstock.name
                %td
                  = image_tag limitedstock.image, width:100
                %td
                  = limitedstock.maker
                %td
                  = limitedstock.current_stock.to_s(:delimited)
= render "shared/adminfooter"

app/views/shared/_adminfooter.html.haml
.adminfooter
  .adminfooter__title
    %span
      Amazon Website Master All right reserved.

app/views/shared/_adminheader.html.haml
.adminheader.clearfix
  .adminheader__title
    = image_tag "logo.png"
    %h1.title
      Website Master
  .adminheader__right.clearfix
    .adminheader__username
      %span
        ようこそ、
        %span.currentuser_name
          = current_user.nickname
        様
    .adminheader__buttons
      .adminheader__buttons__sitebutton
        = link_to "トップページを表示", root_path

app/views/shared/_footer.html.haml
.navLeftFooter
  .navLeftFooter__navFooterBackToTop
    .navLeftFooter__navFooterBackToTop__navFooterBackToTopText
      = link_to "トップへ戻る" , "#"

  .navLeftFooter__navFooterVerticalColumn
    .navLeftFooter__navFooterVerticalColumn__tbody.clearfix
      .navLeftFooter__navFooterVerticalColumn__tbody__tr1
        .navLeftFooter__navFooterVerticalColumn__tbody__tr1_title
          Amazonについて
        .navLeftFooter__navFooterVerticalColumn__tbody__tr1_record
          .ul
            %li<>
              = link_to "採用情報", ""
            %li<>
              = link_to "Amazonについて",""
            %li<>
              = link_to "プレスリリース",""
            %li<>
              = link_to "Amazonと地球", ""
            %li<>
              = link_to "Amazonのコミュニティ活動",""
            %li<>
              = link_to "Amazon Story",""
            %li<>
              = link_to "AmazonGlobal",""
        %td.navFooterColSpacerInner

      .navLeftFooter__navFooterVerticalColumn__tbody__tr2
        .navLeftFooter__navFooterVerticalColumn__tbody__tr2_title
          Amazonでビジネス
        .navLeftFooter__navFooterVerticalColumn__tbody__tr2_record
          .ul
            %li<>
              = link_to "Amazonで売る",""
            %li<>
              = link_to "フルフィルメント by Amazon", ""
            %li<>
              = link_to "Amazon Businessで法人販売",""
            %li<>
              = link_to "アソシエイト（アフィリエイト）",""
            %li<>
              = link_to "Amazonで広告掲載をする",""
            %li<>
              = link_to "Amazonで出版",""
            %li<>
              = link_to "Amazonの仕入先になる",""
            %li<>
              = link_to "›すべてのサービスを見る",""
        %td.navFooterColSpacerInner

      .navLeftFooter__navFooterVerticalColumn__tbody__tr3
        .navLeftFooter__navFooterVerticalColumn__tbody__tr3_title
          Amazonでのお支払い
        .navLeftFooter__navFooterVerticalColumn__tbody__tr3_record
          .ul
            %li<>
              = link_to "Amazonポイント",""
            %li<>
              = link_to "フルフィルメント by Amazon",""
            %li<>
              = link_to "Amazonギフト券",""
            %li<>
              = link_to "Amazon Mastercard",""
            %li<>
              = link_to "クレジットカード＆保険",""
            %li<>
              = link_to "パートナーポイントプログラム",""
            %li<>
              = link_to "Amazonギフト券チャージタイプ",""
            %li<>
              = link_to "すべての支払い方法を見る",""
        %td.navFooterColSpacerInner

      .navLeftFooter__navFooterVerticalColumn__tbody__tr4
        .navLeftFooter__navFooterVerticalColumn__tbody__tr4_title
          ヘルプ＆ガイド
        .navLeftFooter__navFooterVerticalColumn__tbody__tr4_record
          .ul
            %li<>
              = link_to "配送料と配送情報",""
            %li<>
              = link_to "商品の返品・交換",""
            %li<>
              = link_to "コンテンツと端末の管理",""
            %li<>
              = link_to "ストア・特集一覧",""
            %li<>
              = link_to "Amazonアシスタント",""
            %li<>
              = link_to "ヘルプ"
        %td.navFooterColSpacerInner

.navFooterLine
  .nav-logo-base
    = image_tag "logo.png"
  .icp-button#icp-touch-link-country
  .icp-button#icp-touch-link-language

app/views/shared/_header.html.haml
%header
  .navbar{role: "navigation"}
    .nav-over
      .nav-over__left
        = link_to root_path do
          = image_tag "logo.png", class: "logo_image"
      .nav-over__right
        = image_tag "campaign.png"
      .nav-over__center
        .nav-over__center__content
          = form_tag(search_stocks_path, method: :get) do
            .nav-over__center__content__left
              = select_tag 'category_id', options_from_collection_for_select(Category.all, "id", "name"), include_blank: 'すべてのカテゴリ', class: "nav-over__center__content__left__searchselect"
            .nav-over__center__content__center
              .nav-over__center__content__center__search-field
                %input#stock_name_field.nav-over__center__content__center__input{ name: "keyword", placeholder: "", type: "text", value: "" }
                .nav-over__center__content__right
                  = button_tag title: "検索", type: "submit", class: "nav-over__center__content__right__search_btn" do
                    %span.fa.fa-search{"aria-hidden" => "true"}
    .nav-below
      .nav-below__categoly
        = link_to categories_path do
          %span.nav-below__categoly__name カテゴリー
          %span.triangle
        %ul.nav-below__categoly__ul
          %li.nav-below__categoly__li
            = link_to "プライム・ビデオ", "/categories/1/sub_categories/1"
          %li
            = link_to "Amazon Music Unlimited", "/categories/2/sub_categories/6"
          %li
            = link_to "アプリ", "/categories/3/sub_categories/11"
          %li
            = link_to "Echo Dot", "/categories/4/sub_categories/20"
          %li
            = link_to "Fire 7", "/categories/5/sub_categories/23"
          %li
            = link_to "Fire TV Stick", "/categories/6/sub_categories/34"
          %li
            = link_to "Kindle", "/categories/7/sub_categories/42"
          %li
            = link_to "すべてのAmazonフレッシュ", "/categories/8/sub_categories/57"
          %li
            = link_to "本", "/categories/9/sub_categories/74"
          %li
            = link_to "DVD", "/categories/10/sub_categories/94"
          %li
            = link_to "キッチン家電", "/categories/11/sub_categories/104"
          %li
            = link_to "パソコン・タブレット", "/categories/12/sub_categories/127"
          %li
            = link_to "キッチン用品・食器", "/categories/13/sub_categories/153"
          %li
            = link_to "食品・グルメ", "/categories/14/sub_categories/171"
          %li
            = link_to "医薬品", "/categories/15/sub_categories/195"
          %li
            = link_to "ベビー＆マタニティ", "/categories/16/sub_categories/219"
          %li
            = link_to "レディース", "/categories/17/sub_categories/225"
          %li
            = link_to "自転車", "/categories/18/sub_categories/230"
          %li
            = link_to "カー用品", "/categories/19/sub_categories/237"
          %li
            = link_to "Amazon Mastercard", "/categories/20/sub_categories/246"
      .nav-below__amazonpoint
        .nav-below__amazonpoint__mystore
          - if user_signed_in?
            =link_to "マイストア", user_path(current_user), :class => "link"
          - else
            =link_to "マイストア", new_user_session_path, :class => "link"

        .nav-below__amazonpoint__timesale タイムセール
        .nav-below__amazonpoint__gift     ギフト券

      .nav-below__tools
        - if user_signed_in?
          - if current_user.admin_flg == true
            = link_to "管理者の方はこちら", admins_path, class: "nav-below__tools__admin"
        .nav-below__tools__account
          = link_to users_path, :class => "nav-below__tools__account__link" do
            %span.nav-below__tools__account__nickname
            - if user_signed_in?
              = current_user.nickname
              さん
            -else
              ログインしていません
            %span.nav-below__tools__account__list
              アカウント＆リスト
            %span.triangle.triangle__account
          %ul.nav-below__tools__ul
            %li
              .nav-below__tools__ul__left
                %ul.nav-below__tools__ul__inner
                  %li.nav-below__tools__ul__inner__title リスト
                  %li
                    = link_to "ほしい物リスト", ""
                  %li
                    = link_to "映画、DVD", ""
                  %li
                    = link_to "本", ""
                %ul.nav-below__tools__ul__inner
                  %li
                    = link_to "ほしい物リストを作成する", ""
                  %li
                    = link_to "ほしい物リストを見つける", ""
                  %li
                    = link_to "何でもほしい物リスト", ""
              .nav-below__tools__ul__right
                %ul.nav-below__tools__ul__inner
                  %li.nav-below__tools__ul__inner__title アカウントサービス
                  %li
                    = link_to "アカウントサービス", users_path
                  %li
                    = link_to "注文履歴", orders_path
                  %li
                    = link_to "バーチャルダッシュ", ""
                  %li
                    = link_to "ほしい物リスト", ""
                  %li
                    = link_to "おすすめ商品", ""
                  %li
                    = link_to "Amazon定期おトク便情報", ""
                  %li
                    = link_to "Amazonプライム会員情報", ""
                  %li
                    = link_to "ビジネスアカウントを登録", ""
                %ul.nav-below__tools__ul__inner
                  %li
                    = link_to "コンテンツと端末の管理", ""
                  %li
                    = link_to "Prime Music", ""
                  %li
                    = link_to "ミュージックライブラリにアクセス", ""
                  %li
                    = link_to "お客様のAmazon Drive", ""
                  %li
                    = link_to "ウォッチリスト", ""
                  %li
                    = link_to "ビデオライブラリ", ""
                  %li
                    = link_to "お客様のKindle Unlimited", ""
                  %li
                    = link_to "ゲーム&PCソフトダウンロードライブラリ", ""
                  %li
                    = link_to "アプリライブラリとデバイスの管理", ""
                - if user_signed_in?
                  %ul.nav-below__tools__ul__inner
                    %li
                      = link_to "#{current_user.nickname}さんではありませんか？サインアウト", destroy_user_session_path, method: :delete

          .nav-below__categoly
        .nav-below__tools__order
          %span
            = link_to "注文履歴", orders_path
        .nav-below__tools__cart
          = link_to carts_path do
            - if user_signed_in?
              %span
                = gets_cart_itemcount
            - else
              %span
                0
            = image_tag "cart.png"

app/views/shared/_leftsidebar.html.haml
.adminleftwindow
  .adminleftwindow__linkbox
    .adminleftwindow__linkbox__title
      %h2
        商品仕入管理
    .adminleftwindow__linkbox__links
      = link_to "仕入一覧ページ", items_path
    .adminleftwindow__linkbox__links
      = link_to "新規商品を仕入" , new_item_path
    .adminleftwindow__linkbox__links
      = link_to "既存商品を仕入" , addto_items_path
    .adminleftwindow__linkbox__title
      %h2
        在庫状況管理
    .adminleftwindow__linkbox__links
      = link_to "商品一覧ページ", stocks_path
    .adminleftwindow__linkbox__title
      %h2
        売上状況管理
    .adminleftwindow__linkbox__links
      = link_to "Pay.jpログイン", "https://pay.jp/login"
    .adminleftwindow__linkbox__title
      %h2
        ユーザ管理
    .adminleftwindow__linkbox__links
      = link_to "管理者ページ", admins_path
    .adminleftwindow__linkbox__links
      = link_to "管理者情報変更" , edit_user_registration_path
    .adminleftwindow__linkbox__links
      = link_to "権限変更", "/admins/#{current_user.id}/userpermissions"
    .adminleftwindow__linkbox__links
      = link_to "ログアウト" , destroy_user_session_path, method: :delete

app/views/shared/_review.html.haml
.reviews__main__boxes__box
  .reviews__main__boxes__box__topbox
    .reviews__main__boxes__box__topbox__avatar
      = image_tag "face_icon.png", width:40
    .reviews__main__boxes__box__topbox__nickname
      = review.user.nickname
  .reviews__main__boxes__box__middlebox
    .reviews__main__boxes__box__middlebox__rate
      - case review.rate
        - when 1
          .rate.rate10
        - when 2
          .rate.rate20
        - when 3
          .rate.rate30
        - when 4
          .rate.rate40
        - when 5
          .rate.rate50
    .reviews__main__boxes__box__middlebox__title
      = review.title
  .reviews__main__boxes__box__bottombox
    .reviews__main__boxes__box__bottombox__date
      = review.updated_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日")
    .reviews__main__boxes__box__bottombox__text
      = review.review
    .reviews__main__boxes__box__bottombox__links
      - if user_signed_in?
        - if review.user_id == current_user.id
          = link_to "削除" ,stock_review_path(@stock.id ,review.id), method: :delete, remote: true
          = link_to "編集" ,edit_stock_review_path(@stock.id, review.id), method: :patch, remote: true , class: "editreview#{review.id}", id: "editreview#{review.id}"
          %input{id: "selectedstar#{review.id}", type: "hidden", value: review.rate, class: 'selectedstar#{review.id}'}



.edit-modal{id: "editrev#{review.id}"}
  .edittitle
    = form_tag(stock_review_path(@stock.id, review.id), method: :patch, remote: true , id: "target#{review.id}") do
      .edittitle__rate
        レートを選んでください。
      .editevaluation
        %input{id: "editstar#{review.id}_1", :name => "rate", :type => "radio", :value => 5}/
        %label{:for => "editstar#{review.id}_1"}
          ★
        %input{id: "editstar#{review.id}_2", :name => "rate", :type => "radio", :value => 4}/
        %label{:for => "editstar#{review.id}_2"}
          ★
        %input{id: "editstar#{review.id}_3", :name => "rate", :type => "radio", :value => 3}/
        %label{:for => "editstar#{review.id}_3"}
          ★
        %input{id: "editstar#{review.id}_4", :name => "rate", :type => "radio", :value => 2}/
        %label{:for => "editstar#{review.id}_4"}
          ★
        %input{id: "editstar#{review.id}_5", :name => "rate", :type => "radio", :value => 1}/
        %label{:for => "editstar#{review.id}_5"}
          ★
      .edittitle__title
        %p
          レビュータイトルを書いてください。
        %input{ name: "title", size: "40", type: "text", class: "form-title", id: "edit_review__title", value: "#{review.title}"}
        %textarea{ name: "review", type: "text", class: "form-review", id: "edit_review__text"}#{review.review}
      .edittitle__submit
        %input{ name: "stock_id", type: "hidden", value: @stock.id, class: 'stock_id'}
        %input{ type:"submit", value:"送信", class: "graybutton", id: "graybutton"}