config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "stocks#index"

  resources :stocks do
    collection do
      get 'search'
    end
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  get 'stocks/autocomplete_stocks/:term' => 'stocks#autocomplete_stocks'

  resources :items do
    collection do
      get 'addto'
    end
  end
  resources :orders do
    collection do
      get 'confirm'
    end
  end
  resources :admins, only: [:index] do
    resources :userpermissions, only: [:index, :update]
  end
  resources :users, only: [:index, :show, :new] do
    collection do
      get 'payments'
      post 'creditcard_regist'
      delete 'creditcard_destroy'
    end
  end
  resources :carts
  resources :categories do
    collection do
      get 'admin_category'
    end
    resources :sub_categories
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :stock
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!
  before_action :quantitychecker_moveto_buylater

  def index
    # 表示用変数
    @totalyen = 0
    # カート内の商品を取得
    @carts = gets_cart_items
    @totalitems = gets_cart_itemcount
    @carts.each do |cart|
      @totalyen += cart.quantity * Stock.find(cart.stock_id).sell_price
    end
    # あとで買う内の商品を取得
    @buylaters = gets_buylater_items
  end

  def create
    @stocks = Stock.all
    @carts = gets_cart_items
    update_flg = 0
    @carts.each do |cartitem|
      if cartitem.stock_id == cart_params[:stock_id].to_i
        new_quantity = cartitem.quantity + cart_params[:quantity].to_i
        cartitem.update(quantity: new_quantity)
        update_flg = 1
      end
    end
    if update_flg == 0
      @cart = current_user.carts.new(cart_params)
      @cart.save
    else
      @cart = current_user.carts.where(stock_id: cart_params[:stock_id])[0]
    end

    # 合計点数と合計金額の表示
    @carts = current_user.carts.all
    @totalitems = 0
    @totalyen = 0
    @carts.each do |cart|
      @totalitems += cart.quantity
      @totalyen += cart.quantity * Stock.find(cart.stock_id).sell_price
    end

  end

  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    redirect_to carts_path
  end

  def update
    if params[:updflg].to_i == 1
      # jsで数量を更新するとき
      cart = Cart.find(params[:cartid].to_i)
      cart.update(quantity: params[:quantity].to_i)
    else
      # あとで買う,カートにもどすのとき
      cart = Cart.find(params[:id])
      cart.update(cart_params)
    end
    redirect_to carts_path
  end

  private
  def cart_params
    params.require(:cart).permit(:quantity, :stock_id, :buylater_flg, :updflg)
  end

  # 数量セレクトボックスの配列作成
  def quantity_array_maker(stocks)
    @current_stock_array = []
    stocks.current_stock.times do |current_stock|
      if current_stock < 10
        @current_stock_array << [current_stock + 1,current_stock + 1]
      else
        break
      end
    end
    return @current_stock_array
  end

end

app/helpers/carts_helper.rb
module CartsHelper
	# 数量セレクトボックスの配列作成
  def quantity_array_maker(stock)
    @current_stock_array = []
    stock.current_stock.times do |current_stock|
      if current_stock < 10
        @current_stock_array << [current_stock + 1,current_stock + 1]
      else
        break
      end
    end
    return @current_stock_array
  end

  def quantityselecter(cart)
    return cart.quantity - 1
  end
end

app/views/carts/create.html.haml
= render "shared/header"
.add-to-cart
  .add-to-cart__box
    .add-to-cart__box__left
      .add-to-cart__box__left__checkmark
        %i.fa.fa-check.add-to-cart__box__left__checkmark__icon.fa-fw.fa-2x
      .add-to-cart__box__left__image
        = image_tag Stock.find(@cart.stock_id).image
        .add-to-cart__box__left__image__outer
        .add-to-cart__box__left__image__inner
      .add-to-cart__box__left__textbox
        .add-to-cart__box__left__textbox__text
          追加されました
    .add-to-cart__box__center
      .add-to-cart__box__center__text
        .add-to-cart__box__center__text__over
          %span.add-to-cart__box__center__text__over__total
            %b カートの小計（商品
            = @totalitems.to_s(:delimited)
            点）:
          %span.add-to-cart__box__center__text__over__price
            %b{style: "color: red;"}
              ￥
              = @totalyen.to_s(:delimited)
        .add-to-cart__box__center__text__under
          この注文での獲得ポイント: 0pt
    .add-to-cart__box__right
      .add-to-cart__box__right__box
        .showbtn
          = link_to carts_path class: "add-to-cart__box__right__box__showbtn__link" do
            %btn.add-to-cart__box__right__box__showbtn__link__btn カートの編集
        .registerbtn
          = link_to confirm_orders_path class: "add-to-cart__box__right__box__registerbtn__link" do
            %btn.add-to-cart__box__right__box__registerbtn__link__btn レジに進む
.recommends
  .recommends__one
    .recommends__one__title
      この商品に関するスポンサーの商品
    .recommends__one__images
      .btfContent1__uber-widget-ns-images
        - @stocks.shuffle.first(15).each do |stock|
          = link_to image_tag(stock.image), stock_path(stock), width:200, height:200
  .recommends__two
    .recommends__two__title
      もう一度買う
    .recommends__two__images
      .btfContent1__uber-widget-ns-images
        - @stocks.shuffle.first(15).each do |stock|
          = link_to image_tag(stock.image), stock_path(stock), width:200, height:200
  .recommends__three
    .recommends__three__title
      この商品を買った人は、こちらの商品も買っています
    .recommends__three__images
      .btfContent1__uber-widget-ns-images
        - @stocks.shuffle.first(15).each do |stock|
          = link_to image_tag(stock.image), stock_path(stock), width:200, height:200
  .recommends__four
    .recommends__four__title
      この商品をチェックした人は、こちらの商品もチェックしています
    .recommends__four__images
      .btfContent1__uber-widget-ns-images
        - @stocks.shuffle.first(15).each do |stock|
          = link_to image_tag(stock.image), stock_path(stock), width:200, height:200
.carttotal
  .carttotal__text
    カートの小計
  .carttotal__itemcount
    (商品
    = @totalitems.to_s(:delimited)
    点)：
  .carttotal__price
    %b{style: "color: red;"}
      ￥
      = @totalyen.to_s(:delimited)
  .showbtn
    = link_to root_path class: "add-to-cart__box__right__box__showbtn__link" do
      %btn.add-to-cart__box__right__box__showbtn__link__btn カートの編集
  .registerbtn
    = link_to root_path class: "add-to-cart__box__right__box__registerbtn__link" do
      %btn.add-to-cart__box__right__box__registerbtn__link__btn レジに進む

= render "shared/footer"

app/views/carts/index.html.haml
= render "shared/header"
.wrapper.clearfix
  .cartleftwindow
    = link_to "" do
      .cartleftwindow__ad
        .cartleftwindow__ad__card
          = image_tag "cart_ad_1.png", width:138, height:87
        .cartleftwindow__ad__new
          %p.card-title オリコカードTHE POINT新規ご入会者様限定キャンペーン
          %p.card-content ご入会とご利用で最大8,000円相当のオリコポイントをプレゼント！
          %p.card-detail 還元率常時1%！入会後6ヶ月は2%にアップ！
        .cartleftwindow__ad__btn
          = image_tag "cart_ad_2.png", width:125, height:34
    .cartleftwindow__title
      .cartleftwindow__title__left
        ショッピングカート
      .cartleftwindow__title__right
        ご利用可能なAmazonポイントは
        0
        pt です。
        .br
        カートの商品はAmazonポイントの対象外です
    .cartleftwindow__topborder.clearfix
      .cartleftwindow__topborder__container.clearfix
        .cartleftwindow__topborder__pricetext
          価格
        .cartleftwindow__topborder__quantitytext
          数量
      .cartleftwindow__topborder__line
    .cartleftwindow__goodslist
      - @carts.each do |cart|
        .cartleftwindow__goodslist__detail
          .cartleftwindow__goodslist__detail__image
            = link_to stock_path(cart.stock_id) do
              = image_tag Stock.find(cart.stock_id).image, width:200
          .cartleftwindow__goodslist__detail__title
            = link_to stock_path(cart.stock_id) do
              = Stock.find(cart.stock_id).name
          .cartleftwindow__goodslist__detail__maker
            = Stock.find(cart.stock_id).maker
          .cartleftwindow__goodslist__detail__stockcheck
            - if Stock.find(cart.stock_id).current_stock > 5
              .status-green
                在庫あり。
            - elsif Stock.find(cart.stock_id).current_stock == 0
              .status-red
                在庫切れ。入荷予定あり
            - else
              .status-red
                残り
                = Stock.find(cart.stock_id).current_stock
                点。ご注文はお早めに。
          .cartleftwindow__goodslist__detail__primemark
            = image_tag "primemark.png" , width: 50 ,height: 20
          .cartleftwindow__goodslist__detail__giftbox
            / = check_tox_tag("")
            ギフトの設定（贈り主名の表示に必要です）
            = link_to "詳細", ""
          .cartleftwindow__goodslist__detail__destroy
            = link_to "削除", cart_path(cart.id), method: :delete
          .cartleftwindow__goodslist__detail__buylater
            = form_for cart do |f|
              = f.hidden_field :buylater_flg, value: true
              = f.submit value: "あとで買う", class: "btntolink"
        .cartleftwindow__goodslist__pricespace
          .cartleftwindow__goodslist__pricespace__container
            .cartleftwindow__goodslist__pricespace__price
              ¥
              = Stock.find(cart.stock_id).sell_price.to_s(:delimited)
            .cartleftwindow__goodslist__quantityspace
              .cartleftwindow__goodslist__quantity
                = form_for cart do |f|
                  .rightbox__cartbox__quantity
                    / %input{ name: "cartid", type: "hidden", value: cart.id, class: 'cartid'}
                    = f.select :quantity, quantity_array_maker(Stock.find(cart.stock_id)), {selected: cart.quantity}, {id: "quantityselecter#{cart.id}"}
        .cartleftwindow__bottomborder
    .cartleftwindow__subtotal
      .cartleftwindow__subtotal__items
        小計 (
        = @totalitems.to_s(:delimited)
        )点：
      .cartleftwindow__subtotal__total
        ¥
        = @totalyen.to_s(:delimited)
    .cartleftwindow__points
      この注文での獲得ポイント：
      0
      pt
    - if @buylaters.length > 0
      .cartleftwindow__buylatertitle
        .cartleftwindow__buylatertitle__left
          「あとで買う」に入っている商品（
          = @buylaters.length
          点）
      .cartleftwindow__bottomborder
      .cartleftwindow__buylatergoodslist
        - @buylaters.each do |buylater|
          .cartleftwindow__buylatergoodslist__detail
            .cartleftwindow__buylatergoodslist__detail__image
              = image_tag Stock.find(buylater.stock_id).image, width:200
            .cartleftwindow__buylatergoodslist__detail__title
              = Stock.find(buylater.stock_id).name
            .cartleftwindow__buylatergoodslist__detail__maker
              = Stock.find(buylater.stock_id).maker
            .cartleftwindow__buylatergoodslist__detail__stockcheck
              - if Stock.find(buylater.stock_id).current_stock > 5
                .status-green
                  在庫あり。
              - elsif Stock.find(buylater.stock_id).current_stock == 0
                .status-red
                  在庫切れ。入荷予定あり
              - else
                .status-red
                  残り
                  = Stock.find(buylater.stock_id).current_stock
                  点。ご注文はお早めに。
            .cartleftwindow__buylatergoodslist__detail__primemark
              = image_tag "primemark.png" , width: 50 ,height: 20
            .cartleftwindow__buylatergoodslist__detail__destroy
              = link_to "削除", cart_path(buylater.id), method: :delete
            - if buylater.quantity <= Stock.find(buylater.stock_id).current_stock
              .cartleftwindow__buylatergoodslist__detail__movetocart
                = form_for buylater do |f|
                  = f.hidden_field :buylater_flg, value: false
                  = f.submit value: "カートに戻す", class: "btntolink"
          .cartleftwindow__buylatergoodslist__pricespace
            .cartleftwindow__buylatergoodslist__pricespace__price
              ¥
              = Stock.find(buylater.stock_id).sell_price.to_s(:delimited)
          .cartleftwindow__bottomborder
    .cartleftwindow__message
      Amazon.co.jp での商品価格や在庫状況は変更される場合があります。カートに追加した時と在庫状況や価格が異なることがあります。カート内で表示されている価格は最新の価格となります。
      .br
      未登録のAmazonギフト券やクーポンは、お支払い方法選択画面や注文確定画面で入力できます。
  .cartrightwindow
    - if @totalyen > 0
      .cartrightwindow__totalbox
        .cartrightwindow__totalbox__subtotaltext
          小計(
          = @totalitems.to_s(:delimited)
          点)：
          %b{style: "color: #A82207;"}
            ￥
            = @totalyen.to_s(:delimited)
        .cartrightwindow__totalbox__points
          この注文での獲得ポイント：
          0
          pt
        .cartrightwindow__totalbox__giftsettings
          / = check_tox_tag("")
          ギフトの設定（贈り主名の表示に必要です）
        .cartrightwindow__totalbox__registarbtn
          .registerbtn
            = link_to "レジに進む",confirm_orders_path
        .cartrightwindow__totalbox__bordertext
          または
        .cartrightwindow__totalbox__oneclicklinks
          = link_to "サインイン"
          して1-ClickをONにする
    .cartrightwindow__sponsoredgoodslink
      .cartrightwindow__sponsoredgoodslink__title
        カート内の商品に関連するスポンサープロダクト
      .cartrightwindow__sponsoredgoodslink__items
        .cartrightwindow__sponsoredgoodslink__items__image
          = image_tag "prime.png" , width: 96, height: 72
        .cartrightwindow__sponsoredgoodslink__items__goodsname
          SPONSORDGOODSNAME
        .cartrightwindow__sponsoredgoodslink__items__rate
          RATE1
        .cartrightwindow__sponsoredgoodslink__items__price
          ¥1,000
        .cartrightwindow__sponsoredgoodslink__items__primemark
          = image_tag "primemark.png"
        .cartrightwindow__sponsoredgoodslink__items__allitems
          .showbtn__mini
            = link_to "すべての出品を見る",""
= render "shared/footer"