config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "stocks#index"

  resources :stocks do
    collection do
      get 'search'
    end
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  get 'stocks/autocomplete_stocks/:term' => 'stocks#autocomplete_stocks'

  resources :items do
    collection do
      get 'addto'
    end
  end
  resources :orders do
    collection do
      get 'confirm'
    end
  end
  resources :admins, only: [:index] do
    resources :userpermissions, only: [:index, :update]
  end
  resources :users, only: [:index, :show, :new] do
    collection do
      get 'payments'
      post 'creditcard_regist'
      delete 'creditcard_destroy'
    end
  end
  resources :carts
  resources :categories do
    collection do
      get 'admin_category'
    end
    resources :sub_categories
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
  accepts_nested_attributes_for :sub_categories, reject_if: :all_blank

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @category.sub_categories.build
  end

  def create
    @category = Category.new(new_category_params)
    @category.save
    redirect_to admin_category_categories_path
  end

  def edit
    find_category
  end

  def update
    find_category
    @category.update(new_category_params)
    redirect_to admin_category_categories_path
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def admin_category
    @categories = Category.all
  end

  private
  def new_category_params
    params.require(:category).permit(:name,:description, sub_categories_attributes: [:category_id],sub_categories_attributes: [:name])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/admin_category.html.haml
= render "shared/adminheader"
= render "shared/leftsidebar"
.adminmainwindow
  .adminmainwindow__boxes
    .adminmainwindow__boxes__items
      [仕入履歴]
      %table
        %tr
          %th id
          %th name
          %th description
        - @categories.each do |category|
          %tr
            %td
              = category.id
            %td
              = category.name
            %td
              = category.description
            %td
              = link_to "編集", edit_category_path(category.id)
= render "shared/adminfooter"

app/views/categories/edit.html.haml
= render "shared/adminheader"
= render "shared/leftsidebar"
.adminmainwindow
  .adminmainwindow__title
    [カテゴリー編集]
    = form_for @category do |f|
      .adminmainwindow__fields
        = f.label :name, "カテゴリー名"
        = f.text_field :name, placeholder: "カテゴリーを入力してください"
      .adminmainwindow__fields
        = f.label :description, "カテゴリー説明"
        = f.text_field :description, placeholder: "カテゴリー説明を入力してください"
      .adminmainwindow__fields
        = f.submit value: "Send", class: "SendButton"
= render "shared/adminfooter"

app/views/categories/index.html.haml
= render "shared/header"
.categories.clearfix
  - @categories.each do |category|
    .categories_list
      %option.popover-category-name{value: "#{category.id}",} #{category.name}
      %ul.nav_cat_links
        - category.sub_categories.each do |sub_category|
          %li.nav_first
            = link_to sub_category.name, category_sub_category_path(category,sub_category)
= render "shared/footer"

app/views/categories/new.html.haml
= render "shared/adminheader"
= render "shared/leftsidebar"
.adminmainwindow
  .adminmainwindow__title
    [カテゴリー登録]
    = form_for @category do |f|
      .adminmainwindow__fields
        = f.label :name, "カテゴリー名"
        = f.text_field :name, placeholder: "カテゴリーを入力してください"
      .adminmainwindow__fields
        = f.label :description, "カテゴリー説明"
        = f.text_field :description, placeholder: "カテゴリー説明を入力してください"
        = f.fields_for :sub_categories do |g|
          .adminmainwindow__fields
          = g.label :name, "ジャンル"
          = g.text_field :name, placeholder: "ジャンルを入力してください"
      .adminmainwindow__fields
        = f.submit value: "Send", class: "SendButton"
= render "shared/adminfooter"